### ISSUE TITLE
質問3　4章89ページ　インスタンスをvarで生成した時のメンバ変数の扱いについて

### ISSUE THREAD

**Issue by mimuro-lab** [mimuro-lab/Quiz#13]
この章を読んで、swiftにおいてのインスタンス生成も、変数宣言と同様に、`var`と`let`をつけると理解しました。

そこで質問なのですが、
「教科書p89、3行目に`インスタンスの値が、宣言語に変わるときは「var」、変わらないときは「let」を・・・`
とありますが、letで宣言した場合、そのインスタンスの持つメンバ変数の書き換えなどはできるのでしょうか？」

（”インスタンスの値を変えない”という文が理解できませんでした。メンバ変数とかも変わらないという理解で正しいのでしょうか？）

**Comment by TakkuMattsu** [comment]
@mimuro-lab 以下のコードが回答になっているかな？(コードコピーして動かせるはずです)
わからなかったらzoomで聞いてもらって大丈夫です！


http://online.swiftplayground.run/
```
import Foundation

class Human {
    let name: String
    var age: Int = 0
    init(name: String) {
        self.name = name
    }
    func print() -> String {
        return "name:\(name), age:\(age)"
    }
}

class Company {
    let employees: [Human]
    init(employees: [Human]){
        self.employees = employees
    }
}

let employees = [Human(name:"Reimu"),Human(name:"Marisa")]
let company = Company(employees: employees)

for e in company.employees {
    print("before: \(e.print())")
    e.age = 1
    // これはコンパイルエラー
    //e.name = "ZUN"
    print("after: \(e.print())")
}

// これはコンパイルエラー
//company.employees = [Human(name:"Youmu"),Human(name:"Yuyuko")]

```

**Comment by mimuro-lab** [comment]
@TakkuMattsu 
お答えいただき、ありがとうございます。
上記のソースコードを実行してみたところ、以下の様な結果になりました。

```
before: name:Reimu, age:0
after: name:Reimu, age:1
before: name:Marisa, age:0
after: name:Marisa, age:1
```

letでクラスを宣言して、そのあと、メンバ変数ageを直接書き換えているのですね。
つまり、letで宣言したとしても、メンバ変数の書き換えは可能だと分かりました。

私の中で、疑問が解決しました。
解答のためにお時間を割いていただいてありがとうございます。
